title: Tao Ding's Homepage
page-top-title: Tao Ding
top-section-bg-text: Non-Euclidean Statistics, Deep Learning, and Bioinformatics
home-subtitle: Tao Ding&ensp;|&ensp; Postdoctoral Fellow (PI) | Assistant Researcher at ShanghaiTech University
home-description: CSC-founded PhD graduated from Newcastle University (2026 QS: 137th). Research focuses on Non-Euclidean Statistics and Deep Learning, with applications in Bioinformatics, including spatial omics, neuroscience, and biomedical data analysis.
copyright-text: '&copy; Tao Ding. All Rights Reserved.'
