title: Tao Ding's Homepage
page-top-title: Tao Ding
top-section-bg-text: Non-Euclidean Statistics, Deep Learning, and Bioinformatics
home-subtitle: Tao Ding&ensp;|&ensp; Postdoctoral Fellow (PI) | Assistant Researcher at ShanghaiTech University
copyright-text: '&copy; Tao Ding. All Rights Reserved.'
