title: Tao Ding's Homepage
page-top-title: Tao Ding
top-section-bg-text: ’From Huangshan to Newcastle<br>Exploring the world, enjoying life‘
home-subtitle: ‘Dr. Tao DING<br>Postdoctoral Fellow (PI) | Assistant Research<br>ShanghaiTech University’
copyright-text: ‘&copy; Tao Ding. All Rights Reserved.’
